version: '3.9'

services:
  postgres-customer:
    image: postgres:15
    container_name: microservice-amg-postgres-customer
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_customer_data:/var/lib/postgresql/data

  postgres-fraud:
    image: postgres:15
    container_name: microservice-amg-postgres-fraud
    environment:
      POSTGRES_DB: fraud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"  # Porta 5433 no host, 5432 no container
    volumes:
      - postgres_fraud_data:/var/lib/postgresql/data

  customer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: customer
    container_name: microservice-amg-customer
    depends_on:
      - postgres-customer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-customer:5432/customer
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"

  fraud:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: fraud
    container_name: microservice-amg-fraud
    depends_on:
      - postgres-fraud
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-fraud:5432/fraud
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"

volumes:
  postgres_customer_data:
  postgres_fraud_data:
